### ISSUE TITLE
when you set a wait date on a task it doesn't show in the list of "waiting" in the review tab

### ISSUE THREAD

**Issue by silky** [talex5/cuekeeper#5]

**Comment by talex5** [comment]
It should appear on the "Schedule" tab (but not on "Review/Waiting", because it doesn't need to be reviewed). Do you see anything on the schedule tab? There should be a weekly review action by default, at least.

If not, what browser are you using and what version? Do any warnings appear in the browser console?

**Comment by silky** [comment]
my bad, you are right, i see it in the "Schedule" not in the "review" (which is what i meant to report this bug as. apologies.)

**Comment by talex5** [comment]
Yes, that is a bit confusing. I've added a note to the Review/Waiting tab now. Thanks!
